[2024-10-15T11:25:53.193+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T11:25:53.220+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eia_data_ingestion.fetch_and_store_data manual__2024-10-15T11:16:53.804510+00:00 [queued]>
[2024-10-15T11:25:53.242+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eia_data_ingestion.fetch_and_store_data manual__2024-10-15T11:16:53.804510+00:00 [queued]>
[2024-10-15T11:25:53.243+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-15T11:25:53.264+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_and_store_data> on 2024-10-15 11:16:53.804510+00:00
[2024-10-15T11:25:53.278+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'eia_data_ingestion', 'fetch_and_store_data', 'manual__2024-10-15T11:16:53.804510+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpia17s_6a']
[2024-10-15T11:25:53.278+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4436) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T11:25:53.281+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask fetch_and_store_data
[2024-10-15T11:25:53.281+0000] {standard_task_runner.py:72} INFO - Started process 4438 to run task
[2024-10-15T11:25:53.373+0000] {task_command.py:467} INFO - Running <TaskInstance: eia_data_ingestion.fetch_and_store_data manual__2024-10-15T11:16:53.804510+00:00 [running]> on host 7aa864b16460
[2024-10-15T11:25:53.507+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eia_data_ingestion' AIRFLOW_CTX_TASK_ID='fetch_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T11:16:53.804510+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T11:16:53.804510+00:00'
[2024-10-15T11:25:53.509+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-15T11:25:53.510+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-15T11:25:53.511+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_store_data state:running start_date:2024-10-15 11:25:53.221480+00:00
[2024-10-15T11:25:53.511+0000] {logging_mixin.py:190} INFO - Dag name:eia_data_ingestion and current dag run status:running
[2024-10-15T11:25:53.512+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T11:25:56.353+0000] {logging_mixin.py:190} INFO - Fetched 5000 records.
[2024-10-15T11:25:58.206+0000] {logging_mixin.py:190} INFO - Fetched 10000 records.
[2024-10-15T11:25:59.922+0000] {logging_mixin.py:190} INFO - Fetched 15000 records.
[2024-10-15T11:26:01.644+0000] {logging_mixin.py:190} INFO - Fetched 20000 records.
[2024-10-15T11:26:03.613+0000] {logging_mixin.py:190} INFO - Fetched 25000 records.
[2024-10-15T11:26:05.262+0000] {logging_mixin.py:190} INFO - Fetched 30000 records.
[2024-10-15T11:26:06.979+0000] {logging_mixin.py:190} INFO - Fetched 35000 records.
[2024-10-15T11:26:08.749+0000] {logging_mixin.py:190} INFO - Fetched 40000 records.
[2024-10-15T11:26:10.446+0000] {logging_mixin.py:190} INFO - Fetched 45000 records.
[2024-10-15T11:26:12.299+0000] {logging_mixin.py:190} INFO - Fetched 50000 records.
[2024-10-15T11:26:14.241+0000] {logging_mixin.py:190} INFO - Fetched 55000 records.
[2024-10-15T11:26:17.016+0000] {logging_mixin.py:190} INFO - Fetched 60000 records.
[2024-10-15T11:26:18.547+0000] {logging_mixin.py:190} INFO - Fetched 64896 records.
[2024-10-15T11:26:23.862+0000] {logging_mixin.py:190} INFO - Data stored in table 'emission_co2_source'.
[2024-10-15T11:26:25.445+0000] {logging_mixin.py:190} INFO - Fetched 610 records.
[2024-10-15T11:26:28.065+0000] {logging_mixin.py:190} INFO - Data stored in table 'renewable_generation_source'.
[2024-10-15T11:26:29.924+0000] {logging_mixin.py:190} INFO - Fetched 5000 records.
[2024-10-15T11:26:31.744+0000] {logging_mixin.py:190} INFO - Fetched 10000 records.
[2024-10-15T11:26:33.576+0000] {logging_mixin.py:190} INFO - Fetched 15000 records.
[2024-10-15T11:26:35.396+0000] {logging_mixin.py:190} INFO - Fetched 20000 records.
[2024-10-15T11:26:38.403+0000] {logging_mixin.py:190} INFO - Fetched 25000 records.
[2024-10-15T11:26:41.993+0000] {logging_mixin.py:190} INFO - Fetched 30000 records.
[2024-10-15T11:26:44.147+0000] {logging_mixin.py:190} INFO - Fetched 35000 records.
[2024-10-15T11:26:48.284+0000] {logging_mixin.py:190} INFO - Fetched 40000 records.
[2024-10-15T11:27:25.002+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/functions.py", line 85, in process_api_calls
    data = fetch_data(call, api_key, no_of_records=call.get("no_of_records"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/functions.py", line 26, in fetch_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data/?frequency=daily&data%5B0%5D=value&api_key=ixxID9vFalaJnrWYcqNbAPMFRkmKIiC4OJlAGoae&offset=40000
[2024-10-15T11:27:25.048+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-15T11:27:25.049+0000] {logging_mixin.py:190} INFO - Task start:2024-10-15 11:25:53.221480+00:00 end:2024-10-15 11:27:25.047388+00:00 duration:91.825908
[2024-10-15T11:27:25.050+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_and_store_data> dag:<DAG: eia_data_ingestion> dagrun:<DagRun eia_data_ingestion @ 2024-10-15 11:16:53.804510+00:00: manual__2024-10-15T11:16:53.804510+00:00, state:running, queued_at: 2024-10-15 11:16:53.844889+00:00. externally triggered: True>
[2024-10-15T11:27:25.050+0000] {logging_mixin.py:190} INFO - Failure caused by 503 Server Error: Service Unavailable for url: https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data/?frequency=daily&data%5B0%5D=value&api_key=ixxID9vFalaJnrWYcqNbAPMFRkmKIiC4OJlAGoae&offset=40000
[2024-10-15T11:27:25.051+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=eia_data_ingestion, task_id=fetch_and_store_data, run_id=manual__2024-10-15T11:16:53.804510+00:00, execution_date=20241015T111653, start_date=20241015T112553, end_date=20241015T112725
[2024-10-15T11:27:25.080+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T11:27:25.081+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task fetch_and_store_data (503 Server Error: Service Unavailable for url: https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data/?frequency=daily&data%5B0%5D=value&api_key=ixxID9vFalaJnrWYcqNbAPMFRkmKIiC4OJlAGoae&offset=40000; 4438)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/functions.py", line 85, in process_api_calls
    data = fetch_data(call, api_key, no_of_records=call.get("no_of_records"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/functions.py", line 26, in fetch_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data/?frequency=daily&data%5B0%5D=value&api_key=ixxID9vFalaJnrWYcqNbAPMFRkmKIiC4OJlAGoae&offset=40000
[2024-10-15T11:27:25.149+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T11:27:25.183+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T11:27:25.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
